### ISSUE TITLE
貌似仅仅是一个dva相关的项目，model下面没有readme里面的内容

### ISSUE THREAD

**Issue by hfuuss** [jiangshanmeta/react-admin#1]
还没有开始做吗？

**Comment by jiangshanmeta** [comment]
@hfuuss   和dva无关。

model 下是有 readme 相关的 内容的 [一个model示例](https://github.com/jiangshanmeta/react-admin/blob/master/src/models/userModel.js) 。这个文件就是一个例子，包含readme提到的fieldList operators 等各项配置。。

终于有人想看看我的项目啦，有点小激动

**Comment by hfuuss** [comment]
@jiangshanmeta Soga，，，我拉的那会貌似还没有更新。很迷

**Comment by jiangshanmeta** [comment]
@hfuuss  这个目录下有东西已经好久了，大概是打开的姿势不对吧（逃

**Comment by hfuuss** [comment]
@jiangshanmeta Soga，我最近也在想做这个东西
